# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Alinx/Alinx7010/Self_learning/axidma_axiuart/axidma_axiuart/axidma_axiuart.srcs/sources_1/ip/rxdata_distmem/rxdata_distmem.xci
# IP: The module: 'rxdata_distmem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Alinx/Alinx7010/Self_learning/axidma_axiuart/axidma_axiuart/axidma_axiuart.srcs/sources_1/ip/rxdata_distmem/rxdata_distmem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rxdata_distmem'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/Alinx/Alinx7010/Self_learning/axidma_axiuart/axidma_axiuart/axidma_axiuart.srcs/sources_1/ip/rxdata_distmem/rxdata_distmem.xci
# IP: The module: 'rxdata_distmem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Alinx/Alinx7010/Self_learning/axidma_axiuart/axidma_axiuart/axidma_axiuart.srcs/sources_1/ip/rxdata_distmem/rxdata_distmem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rxdata_distmem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
