# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Alinx/Alinx7010/Self_learning/axidma_axiuart/axidma_axiuart/axidma_axiuart.srcs/sources_1/ip/blk_mem_gen_rx/blk_mem_gen_rx.xci
# IP: The module: 'blk_mem_gen_rx' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Alinx/Alinx7010/Self_learning/axidma_axiuart/axidma_axiuart/axidma_axiuart.srcs/sources_1/ip/blk_mem_gen_rx/blk_mem_gen_rx_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_rx'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Alinx/Alinx7010/Self_learning/axidma_axiuart/axidma_axiuart/axidma_axiuart.srcs/sources_1/ip/blk_mem_gen_rx/blk_mem_gen_rx.xci
# IP: The module: 'blk_mem_gen_rx' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Alinx/Alinx7010/Self_learning/axidma_axiuart/axidma_axiuart/axidma_axiuart.srcs/sources_1/ip/blk_mem_gen_rx/blk_mem_gen_rx_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_rx'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
