# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Alinx/Alinx7010/Self_learning/axidma_axiuartlite/axidma_axiuartlite.srcs/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
# IP: The module: 'system_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Alinx/Alinx7010/Self_learning/axidma_axiuartlite/axidma_axiuartlite.srcs/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/Alinx/Alinx7010/Self_learning/axidma_axiuartlite/axidma_axiuartlite.srcs/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
# IP: The module: 'system_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Alinx/Alinx7010/Self_learning/axidma_axiuartlite/axidma_axiuartlite.srcs/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
